--
-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to You under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--      https://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

drop table t_demo if exists;

create table t_demo
(
    id                 integer generated by default as identity,
    name               varchar(100),
    pwd                varchar(100),
    version            integer  default 0,
    enabled            integer  default 1,
    last_modified_by   integer  default 0,
    last_modified_date datetime default null,
    disabled_date      datetime default null,
    sex                integer  default 0,
    primary key (id)
);

insert into t_demo (id, name, version, pwd, enabled)
values (1, 'root1', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (2, 'root2', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (3, 'root3', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (4, 'root4', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (5, 'root5', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (6, 'root6', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (7, 'root7', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (8, 'root8', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (9, 'root9', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (10, 'root10', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (11, 'root11', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (12, 'root12', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (13, 'root13', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (14, 'root14', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (15, 'root15', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (16, 'root16', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (17, 'root17', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (18, 'root18', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (19, 'root19', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (20, 'root20', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (21, 'root21', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (22, 'root22', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (23, 'root23', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (24, 'root24', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (25, 'root25', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (26, 'root26', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (27, 'root27', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (28, 'root28', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (29, 'root29', 0, '123456', 1);
insert into t_demo (id, name, version, pwd, enabled)
values (30, 'root30', 0, '123456', 1);
